CREATE ROLE KUNDE_ROLLE;
CREATE ROLE GESCHAEFTSFUEHRER_ROLLE;
CREATE ROLE ADMINISTRATOR_ROLLE;
CREATE ROLE MITARBEITER_ROLLE;


-- Admin Rolle
-- Rechte auf alle Tabellen außer UPDATE und DELTE von LOG
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA KrautUndRueben TO ADMINISTRATOR_ROLLE;
REVOKE UPDATE, DELETE ON LOG FROM ADMINISTATOR_ROLLE;


-- Geschäftsführer Rolle
-- Darf nur die View zum Umsatz pro Rezept lesen
GRANT SELECT ON view_show_general_sales TO GESCHAEFTSFUEHRER_ROLLE;


-- Mitarbeiter Rolle
GRANT SELECT, INSERT, UPDATE ON 
    REZEPT, ERNAEHRUNGSKATEGORIE, REZEPT_ZUTAT, ZUTAT, ZUTAT_NAEHRWERT, VERSANDINF
TO MITARBEITER_ROLLE;

GRANT SELECT ON view_KONTOINFORMATIONEN TO MITARBEITER_ROLLE;

REVOKE ALL ON ROLLE, LOG FROM MITARBEITER_ROLLE;

-- Kunden Rolle
GRANT SELECT ON 
    REZEPT, ERNAEHRUNGSKATEGORIE, REZEPT_ERNAEHRUNGSKATEGORIE, REZEPT_ZUTAT, ZUTAT_ALLERGEN, ZUTAT_NAEHRWERT
TO KUNDE_ROLLE; 

-- Zugriff zu alle Attributen außer Lagermenge von ZUTAT
GRANT SELECT (ZUTATENID, NAME, GROESSE, KATEGORIE, PREIS_EINHEIT, EINHEIT) ON ZUTAT TO KUNDE_ROLLE;
-- Kundenspezifische Views zu Bestellinformationen und Kontoinformationen
GRANT SELECT ON view_KUNDEBESTELLINFORMATIONEN, view_KONTOINFORMATIONEN TO KUNDE_ROLLE;

REVOKE ALL ON
    MITARBEITER, ROLLE, LOG, LIEFERANT
TO KUNDE_ROLLE;

