-- CTE, die alle Kontoinformationen zusammen fasst. Grundlage für darauf aufbauende Views.
WITH cte_KONTOINFORMATIONEN AS
SELECT *
FROM BESTELLUNG b
JOIN RECHNUNG r ON b.BESTELLNR = r.BESTELLNR
JOIN VERSANDINF v ON v.BESTELLNR = b.BESTELLNR
JOIN KUNDE k ON k.KUNDENID = b.KUNDENID
JOIN KONTO ko ON ko.KUNDENID = k.KUNDENID
JOIN PERSOENLINF p ON p.KUNDENID = k.KUNDENID
JOIN ADDRESSE a ON a.KUNDENID = k.KUNDENID
; 