-- View um die Informationen über das eigene Konto des Kunden anzuzeigen
CREATE OR REPLACE VIEW view_KUNDENKONTOINFORMATIONEN AS
SELECT 
    VORNAME
    , NACHNAME
    , EMAIL
    , STRASSE
    , HAUSNR
    , PLZ
    , STADT
    , GROUP_CONCAT(a.NAME) AS Allergene
FROM cte_KONTOINFORMATIONEN c
JOIN KUNDE_ALLERGEN ka ON c.KUNDENID = ka.KUNDENID
JOIN ALLERGEN a ON ka.ALLERGENID = a.ALLERGENID
WHERE (DB_LOGIN_NAME = SUBSTRING_INDEX(USER(), '@',1))
GROUP BY c.KUNDENID
;