-- VIEW, die nur die Bestellinformationen für den Kunden enthält.

CREATE OR REPLACE VIEW view_KUNDEBESTELLINFORMATIONEN AS
SELECT
    BESTELLNR
    , LIEFERDATUM
    , STORNIERT
    , RECHNUNGSNR
    , GESAMTPREIS
    , RECHNUNGSDATUM
    , RECHNUNGSFRIST
    , BEZAHLT
    , VERSANDNR
    , VERSANDDATUM
    , VERSANDDIENST
    , UEBERGABEDATUM
FROM cte_KONTOINFORMATIONEN
WHERE (DB_LOGIN_NAME = SUBSTRING_INDEX(USER(), '@',1))
; 