CREATE TABLE IF NOT EXISTS BESTELLUNG_REZEPT (
    BESTELLNR INT NOT NULL,
    REZEPTID INT NOT NULL,
    REZEPTMENGE INT NOT NULL,
    PRIMARY KEY (REZEPTID, BESTELLNR),
    FOREIGN KEY (REZEPTID) REFERENCES REZEPT(REZEPTID) ON DELETE RESTRICT,
    FOREIGN KEY (BESTELLNR) REFERENCES BESTELLUNG(BESTELLNR) ON DELETE CASCADE
);