CREATE TABLE IF NOT EXISTS REZEPT_ERNAEHRUNGSKATEGORIE (
    REZEPTID INT NOT NULL,
    ERNAEHRUNGSKATEGORIEID INT NOT NULL,
    PRIMARY KEY (REZEPTID, ERNAEHRUNGSKATEGORIEID),
    FOREIGN KEY (REZEPTID) REFERENCES REZEPT(REZEPTID) ON DELETE CASCADE,
    FOREIGN KEY (ERNAEHRUNGSKATEGORIEID) REFERENCES ERNAEHRUNGSKATEGORIE(ERNAEHRUNGSKATEGORIEID) ON DELETE CASCADE
);