CREATE TABLE IF NOT EXISTS MITARBEITER (
    MITARBEITERID INT AUTO_INCREMENT PRIMARY KEY,
    PERSOENLINFID INT NOT NULL,
    ADRESSENID INT NOT NULL,
    KONTOID INT NOT NULL,
    FOREIGN KEY (KONTOID) REFERENCES KONTO(KONTOID) ON DELETE RESTRICT,
    FOREIGN KEY (PERSOENLINFID) REFERENCES PERSOENLINF(PERSOENLINFID) ON DELETE RESTRICT,
    FOREIGN KEY (ADRESSENID) REFERENCES ADRESSE(ADRESSENID) ON DELETE RESTRICT
);
