CREATE TABLE IF NOT EXISTS ZUTAT_ALLERGEN (
   ZUTATENID INT NOT NULL,
   ALLERGENID INT NOT NULL,
   PRIMARY KEY (ZUTATENID, ALLERGENID),
   FOREIGN KEY (ZUTATENID) REFERENCES ZUTAT(ZUTATENID) ON DELETE CASCADE,
   FOREIGN KEY (ALLERGENID) REFERENCES ALLERGEN(ALLERGENID) ON DELETE RESTRICT
); 
