CREATE TABLE IF NOT EXISTS LIEFERANT_ZUTAT (
    ZUTATENID INT NOT NULL,
    LIEFERANTENID INT NOT NULL,
    PRIMARY KEY (ZUTATENID, LIEFERANTENID),
    FOREIGN KEY (LIEFERANTENID) REFERENCES LIEFERANT(LIEFERANTENID) ON DELETE RESTRICT,
    FOREIGN KEY (ZUTATENID) REFERENCES ZUTAT(ZUTATENID) ON DELETE CASCADE
);