CREATE TABLE IF NOT EXISTS DSERKLAERUNG (
    DSE_ID INT AUTO_INCREMENT PRIMARY KEY,
    DSE_VERSION INT NOT NULL,
    ZUGESTIMMT_AM DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    WIDERRUFEN_AM DATETIME
);