CREATE TABLE IF NOT EXISTS BESTELLUNG (
    BESTELLNR INT PRIMARY KEY,
    KUNDENID INT NOT NULL,
    STORNIERT BOOLEAN,
    VERSANDNR INT,
    RECHNUNGSNR INT,
    FOREIGN KEY (KUNDENID) REFERENCES KUNDE(KUNDENID) ON DELETE RESTRICT,
    FOREIGN KEY (VERSANDNR) REFERENCES VERSANDINF(VERSANDNR) ON DELETE RESTRICT,
    FOREIGN KEY (RECHNUNGSNR) REFERENCES RECHNUNG(RECHNUNGSNR) ON DELETE RESTRICT
);
