CREATE TABLE IF NOT EXISTS KUNDE (
    KUNDENID INT AUTO_INCREMENT PRIMARY KEY,
    PERSOENLINFID INT,
    ADRESSENID INT,
    KONTOID INT,
    DSE_ID INT,
    FOREIGN KEY (PERSOENLINFID) REFERENCES PERSOENLINF(PERSOENLINFID) ON DELETE SET NULL,
    FOREIGN KEY (KONTOID) REFERENCES KONTO(KONTOID) ON DELETE SET NULL,
    FOREIGN KEY (ADRESSENID) REFERENCES ADRESSE(ADRESSENID) ON DELETE SET NULL,
    FOREIGN KEY (DSE_ID) REFERENCES DSERKLAERUNG(DSE_ID) ON DELETE SET NULL
);