CREATE TABLE IF NOT EXISTS BESTELLUNG_ZUTAT (
    BESTELLNR INT NOT NULL,
    ZUTATENID INT NOT NULL,
    BESTELLUNG_ZUTATENMENGE INT NOT NULL,
    PRIMARY KEY (ZUTATENID, BESTELLNR),
    FOREIGN KEY (ZUTATENID) REFERENCES ZUTAT(ZUTATENID) ON DELETE RESTRICT,
    FOREIGN KEY (BESTELLNR) REFERENCES BESTELLUNG(BESTELLNR) ON DELETE CASCADE
);
