CREATE TABLE IF NOT EXISTS REZEPT_ZUTAT (
    REZEPTID INT NOT NULL,
    ZUTATENID INT NOT NULL,
    REZEPT_ZUTATENMENGE INT NOT NULL,
    PRIMARY KEY (REZEPTID, ZUTATENID),
    FOREIGN KEY (REZEPTID) REFERENCES REZEPT(REZEPTID) ON DELETE CASCADE,
    FOREIGN KEY (ZUTATENID) REFERENCES ZUTAT(ZUTATENID) ON DELETE RESTRICT
);