CREATE TABLE IF NOT EXISTS KONTO (
    KONTOID INT PRIMARY KEY,
    KUNDENID INT NOT NULL,
    EMAIL VARCHAR(150) UNIQUE NOT NULL,
    PASSWORT VARCHAR(255) NOT NULL,
    AKTIV BOOLEAN DEFAULT FALSE,
    LETZTE_ANMELDUNG TIMESTAMP NULL,
    ERSTELLUNGS_DATUM TIMESTAMP NOT NULL
);