CREATE TABLE IF NOT EXISTS KUNDE_ALLERGEN (
    KUNDENID INT NOT NULL,
    ALLERGENID INT NOT NULL,
    PRIMARY KEY (KUNDENID, ALLERGENID),
    FOREIGN KEY (KUNDENID) REFERENCES KUNDE(KUNDENID) ON DELETE CASCADE,
    FOREIGN KEY (ALLERGENID) REFERENCES ALLERGEN(ALLERGENID) ON DELETE RESTRICT
);