-- Kombinierte Filter: Zeigt Rezepte an, die sowohl weniger als fünf Zutaten enthalten als auch eine bestimmte Ernährungskategorie erfüllen.
WITH alle_zutaten AS (
SELECT
b.BESTELLNR,
zn.FETT_G * bz.ZUTATENMENGE AS FETT_G,
zn.ZUCKER_G * bz.ZUTATENMENGE AS ZUCKER_G,
zn.KOHLENHYDRATE_G * bz.ZUTATENMENGE AS KOHLENHYDRATE_G,
zn.PROTEIN_G * bz.ZUTATENMENGE AS PROTEIN_G,
zn.KALORIEN_KCAL * bz.ZUTATENMENGE AS KALORIEN_KCAL,
zn.NATRIUM_G * bz.ZUTATENMENGE AS NATRIUM_G,
zn.GESAETTIGTE_FETTSAUREN_G * bz.ZUTATENMENGE AS GESAETTIGTE_FETTSAUREN_G,
zn.BALLASTSTOFFE_G * bz.ZUTATENMENGE AS zn.BALLASTSTOFFE_G,
bz.ZUTATENMENGE AS MENGE
FROM BESTELLUNG b
JOIN BESTELLUNG_ZUTAT bz ON b.BESTELLNR = bz.BESTELLNR
JOIN ZUTAT z ON bz.ZUTATENID = z.ZUTATENID
JOIN ZUTAT_NAEHRWERT zn ON z.ZUTATENID = zn.ZUTATENID
UNION ALL
SELECT
b.BESTELLNR,
zn.FETT_G * (rz.ZUTATENMENGE * br.MENGE) AS FETT_G,
zn.ZUCKER_G * (rz.ZUTATENMENGE * br.MENGE) AS ZUCKER_G,
zn.KOHLENHYDRATE_G * (rz.ZUTATENMENGE * br.ZUTATENMENGE) AS KOHLENHYDRATE_G,
zn.PROTEIN_G * (rz.ZUTATENMENGE * br.ZUTATENMENGE) AS PROTEIN_G,
zn.KALORIEN_KCAL * (rz.ZUTATENMENGE * br.ZUTATENMENGE) AS KALORIEN_KCAL,
zn.NATRIUM_G * (rz.ZUTATENMENGE * br.ZUTATENMENGE) AS AS NATRIUM_G,
zn.GESAETTIGTE_FETTSAUREN_G * (rz.ZUTATENMENGE * br.ZUTATENMENGE) AS GESAETTIGTE_FETTSAUREN_G,
zn.BALLASTSTOFFE_G * (rz.ZUTATENMENGE * br.ZUTATENMENGE) AS zn.BALLASTSTOFFE_G
(rz.ZUTATENMENGE * br.ZUTATENMENGE) AS MENGE
FROM BESTELLUNG b
JOIN BESTELLUNG_REZEPT br ON b.BESTELLNR = br.BESTELLNR
JOIN REZEPT r ON br.REZEPTID = r.REZEPTID
JOIN REZEPT_ZUTAT rz ON r.REZEPTID = rz.REZEPTID
JOIN ZUTAT z ON rz.ZUTATENID = z.ZUTATENID
JOIN ZUTAT_NAEHRWERT zn ON z.ZUTATENID = zn.ZUTATENID
)
SELECT
b.BESTELLNR AS Bestellnummer,
ROUND((SUM(az.FETT_G) / SUM(az.MENGE)) * 100, 2) AS "Fett pro 100 g"
ROUND((SUM(az.ZUCKER_G) / SUM(az.MENGE)) * 100, 2) AS "Zucker pro 100 g"
ROUND((SUM(az.KOHLENHYDRATE_G) / SUM(az.MENGE)) * 100, 2) AS "Kohlenhydrate pro 100 g"
ROUND((SUM(az.PROTEIN_G) / SUM(az.MENGE)) * 100, 2) AS "Protein pro 100 g"
ROUND((SUM(az.KALORIEN_KCAL) / SUM(az.MENGE)) * 100, 2) AS "Kalorien pro 100 g"
ROUND((SUM(az.NATRIUM_G) / SUM(az.MENGE)) * 100, 2) AS "Natrium pro 100 g"
ROUND((SUM(az.GESAETTIGTE_FETTSAUREN_G) / SUM(az.MENGE)) * 100, 2) AS "Gesaettigte Fettsaueren pro 100 g"
ROUND((SUM(az.BALLASTSTOFFE_G) / SUM(az.MENGE)) * 100, 2) AS "Ballaststoffe pro 100 g"
FROM alle_zutaten az
JOIN BESTELLUNG b ON az.BESTELLNR = b.BESTELLNR
JOIN KUNDE k ON b.KUNDENID = k.KUNDENID
WHERE k.KUNDENID = ?
GROUP BY b.BESTELLNR
ORDER BY b.BESTELLNR;