-- Anzahl Rezepte nach Ernährungskategorie
-- GROUP BY, AGG, JOIN

SELECT
e.NAME AS Ernährungskategorie,
COUNT(e.ERNAEHRUNGSKATEGORIEID) AS 'Anzahl Rezepte pro Kategorie'
FROM REZEPT r
JOIN REZEPT_ERNAEHRUNGSKATEGORIE re ON r.REZEPTID = re.REZEPTID
JOIN ERNAEHRUNGSKATEGORIE e ON re.ERNAEHRUNGSKATEGORIEID = e.ERNAEHRUNGSKATEGORIEID
GROUP BY ERNAEHRUNGSKATEGORIE
;