CREATE TABLE IF NOT EXISTS KUNDE (
    KUNDENID INT AUTO_INCREMENT PRIMARY KEY,
    PERSOENLINFID INT NOT NULL,
    ADRESSENID INT NOT NULL,
    KONTOID INT NOT NULL,
    FOREIGN KEY (PERSOENLINFID) REFERENCES PERSOENLINF(PERSOENLINFID) ON DELETE RESTRICT,
    FOREIGN KEY (KONTOID) REFERENCES KONTO(KONTOID) ON DELETE RESTRICT,
    FOREIGN KEY (ADRESSENID) REFERENCES ADRESSE(ADRESSENID) ON DELETE RESTRICT
);