CREATE TABLE IF NOT EXISTS LIEFERANT (
    LIEFERANTENID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(150) UNIQUE,
    ADRESSENID INT NOT NULL,
    FOREIGN KEY (ADRESSENID) REFERENCES ADRESSE(ADRESSENID) ON DELETE RESTRICT
);
