CREATE TABLE IF NOT EXISTS ZUTAT (
    ZUTATENID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(150) NOT NULL,
    KATEGORIE VARCHAR(10) NOT NULL,
    GROESSE INT NOT NULL,
    LAGERMENGE INT,
    EINHEIT VARCHAR(6) NOT NULL, -- l, ml, g, mg, Anzahl
    PREIS_EINHEIT INT NOT NULL
);
