CREATE TABLE IF NOT EXISTS MITARBEITER_ROLLE (
    MITARBEITERID INT NOT NULL,
    ROLLEID INT NOT NULL,
    PRIMARY KEY (ROLLEID, MITARBEITERID),
    FOREIGN KEY (ROLLEID) REFERENCES ROLLE(ROLLEID) ON DELETE CASCADE,
    FOREIGN KEY (MITARBEITERID) REFERENCES MITARBEITER(MITARBEITERID) ON DELETE CASCADE
);