CREATE TABLE IF NOT EXISTS REZEPT (
    REZEPTID INT AUTO_INCREMENT PRIMARY KEY,
    NAME VARCHAR(150) NOT NULL,
    URHEBER VARCHAR(100),
    GEAENDERT_AM DATETIME ON UPDATE CURRENT_TIMESTAMP,
    ERSTELLT_AM DATETIME DEFAULT CURRENT_TIMESTAMP,
    ANLEITUNG TEXT,
    PORTIONEN INT DEFAULT 1,
    ZUBEREITUNGSZEIT INT,
    ERNAEHRUNGSKATEGORIEID INT,
    FOREIGN KEY (ERNAEHRUNGSKATEGORIEID) REFERENCES ERNAEHRUNGSKATEGORIE(ERNAEHRUNGSKATEGORIEID) ON DELETE RESTRICT,
);
