CREATE TABLE IF NOT EXISTS LOG (
    LOGID INT AUTO_INCREMENT PRIMARY KEY,
    MITARBEITERID INT,
    AKTION VARCHAR(100),
    ZIELTABELLE VARCHAR(100),
    ZIELID VARCHAR(100),
    TIMESTAMP DATETIME DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MITARBEITERID) REFERENCES MITARBEITER(MITARBEITERID)
);
