CREATE TABLE IF NOT EXISTS ZUTAT_NAEHRWERT (
    ZUTATENID INT NOT NULL UNIQUE,
    KALORIEN_KCAL DECIMAL(10,2),
    PROTEIN_G DECIMAL(10,3),
    KOHLENHYDRATE_G DECIMAL(10,3),
    ZUCKER_G DECIMAL(10,3),
    FETT_G DECIMAL(10,3),
    GESAETTIGTE_FETTSAUREN_G DECIMAL(10,3),
    BALLASTSTOFFE_G DECIMAL(10,3),
    NATRIUM_G DECIMAL(10,3),
    FOREIGN KEY (ZUTATENID) REFERENCES ZUTAT(ZUTATENID) ON DELETE CASCADE
);
